USEMODULE += iolist
USEMODULE += netdev_legacy_api
USEPKG += driver_sx126x
FEATURES_REQUIRED += periph_gpio_irq

ifneq (,$(filter ieee802154,$(USEMODULE)))
    USEMODULE += sx126x_radio_hal
    USEMODULE += checksum
else
    USEMODULE += lora
endif