include $(RIOTBOARD)/common/nucleo32/Makefile.dep
ifneq (,$(filter netdev_default,$(USEMODULE)))
  USEMODULE += sx1276
endif
ifneq (,$(filter ieee802154,$(USEMODULE)))
  USEMODULE += ieee802154_submac
endif

